Check for tcmalloc in system paths also

diff --git a/bin/opensfm b/bin/opensfm
--- a/bin/opensfm
+++ b/bin/opensfm
@@ -10,7 +10,14 @@ else
 fi
 
 if [ "$(uname)" == "Linux" ]; then
-    export LD_PRELOAD=$CONDA_PREFIX/lib/libtcmalloc.so
+   if [ -f "$CONDA_PREFIX/lib/libtcmalloc.so" ]; then
+      export LD_PRELOAD=$CONDA_PREFIX/lib/libtcmalloc.so
+   elif [ -f "/usr/lib/x86_64-linux-gnu/libtcmalloc.so" ]; then
+      export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so
+   else
+      echo "Can't find libtcmalloc. tcmalloc is mandatory for running OpenSfM."
+      exit 1
+   fi
 fi
 
 "$PYTHON" "$DIR"/opensfm_main.py "$@"
